// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDF5TVPl9qpzML0j5oBmzOKYzosZQnuEDQ',
    appId: '1:284404919671:web:e2b9e722aaed9cd2204572',
    messagingSenderId: '284404919671',
    projectId: 'walkingapp-366812',
    authDomain: 'walkingapp-366812.firebaseapp.com',
    storageBucket: 'walkingapp-366812.appspot.com',
    measurementId: 'G-NX4CSSPPWP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwsdQkSd7XWrNqFBQcDpZQPqzTFrDz8ns',
    appId: '1:284404919671:android:f9c080e48e28a66f204572',
    messagingSenderId: '284404919671',
    projectId: 'walkingapp-366812',
    storageBucket: 'walkingapp-366812.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkOD2DRNUOjVyA0NH-O6xvZ7N2TSJ6lZc',
    appId: '1:284404919671:ios:5f4654896bd5ca8c204572',
    messagingSenderId: '284404919671',
    projectId: 'walkingapp-366812',
    storageBucket: 'walkingapp-366812.appspot.com',
    iosClientId: '284404919671-tvue403ts06f6fnttvto41962b0p567a.apps.googleusercontent.com',
    iosBundleId: 'com.glion.WalkingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0aYikkbFOx9dwgFkx7BC0wKW4wAlr4ZM',
    appId: '1:284404919671:ios:d4c6447615c1a1ba204572',
    messagingSenderId: '284404919671',
    projectId: 'walkingapp-366812',
    storageBucket: 'walkingapp-366812.appspot.com',
    iosClientId: '284404919671-co8m2mf0bl6vdv2ecsivtmh4gut1vpdu.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterWorkingapp',
  );
}
